### ISSUE TITLE
Persistent_term for storing configuration 

### ISSUE THREAD

**Issue by dowusu** [karlseguin/dcache#1]
I was wondering if there will be a performance gain using persistent_term to store the configuration rather than ets since it's optimized for reading.
I must admit I'm yet to run any meaningful benchmark . Sorry for using this channel as this is not more of an issue. Early adopter question.
Great work

**Comment by karlseguin** [comment]
I hadn't thought about that.

It's a pretty good idea, but I wonder if keeping it as-is makes DCache.setup useful for short-lived caches (though, I've never had such a use for that). Using persistent_term if caches will come and go frequently wouldn't be great.

Any features you'd like to see, or direction you'd like me to explore otherwise?

**Comment by dowusu** [comment]
My bad,  missed the section of deleting configuration item, persistent_term isn't great when it comes to deletion. I had a bit of time to peruse portions of the code, I was wondering if the expiry/ttl could be based on the monotonic time.

Checked the erlang doc and still now sure how `:erlang.system_time` handles changes of the system time especially in my production context where occasionally my system time is adjusted to sync with the ntp server.

Being able to pass a match spec to do purging will be nice and also scheduling of the purging.

**Comment by karlseguin** [comment]
I switched to `:erlang.monotonic_time/1`.

Not sure about having built-in scheduling for purging, but I expanded the API so that this should be easy to do externally. I added a `:none` purger and exposed the `reduce_segments/2` and `each_segments/2` as well as some helpers to deal with an `entry` without having to hard-code the `{key, value, expiry}` pattern.

**Comment by dowusu** [comment]
Great, BTW  I've learnt a great deal from this project. Just finished reading the blog on it as well. I think there is a typo/errata WRT `:erlang.system_clock(:second)` as that function is non-existent. I inferred it as `:erlang.system_time(:second)`. The `put/3` doesn't use the ttl parameter;  `:erlang.system_clock(:second) + ttl`(inferred). Maybe finally I've a use case for `:persistent_term` by storing `max_size` configuration outside the ets table since it won't be modified, persistent_term is great for reading and just a tad of separation of concern.
